AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  GitHubAccount:
    Type: String
    Description: The GitHub account name
Resources:
  GitHubCDKRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubAccount}/*'
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
      Policies:
        - PolicyName: GitHubCDKActionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: '*'
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource: 'arn:aws:iam::*:role/cdk-*'
  GitHubCLIRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubAccount}/*'
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      Policies:
        - PolicyName: GitHubCLIPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - 'cloudfront:GetInvalidation'
                  - 'cloudfront:CreateInvalidation'
                Resource: '*'
Outputs:
  GitHubCDKRoleArn:
    Description: The ARN of the GitHub CDK role
    Value: !GetAtt GitHubCDKRole.Arn
  GitHubCDKRoleName:
    Description: The name of the GitHub CDK role
    Value: !Ref GitHubCDKRole
  GitHubCLIRoleArn:
    Description: The ARN of the GitHub CLI role
    Value: !GetAtt GitHubCLIRole.Arn
  GitHubCLIRoleName:
    Description: The name of the GitHub CLI role
    Value: !Ref GitHubCLIRole