AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  GitHubAccount:
    Type: String
    Description: The GitHub account name
Resources:
  GitHubRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubAccount}/*'
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
      Policies:
        - PolicyName: GitHubActionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: '*'
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource: 'arn:aws:iam::*:role/cdk-*'
Outputs:
  RoleArn:
    Description: The ARN of the GitHub role
    Value: !GetAtt GitHubRole.Arn
  RoleName:
    Description: The name of the GitHub role
    Value: !Ref GitHubRole